### PR TITLE
Implement FromDer trait and DerIterator type

### PR DESCRIPTION
**Pull request by djc**
Right now this is only a little bit more concise but I feel like it might help structure things going forward?

Needs a thorough audit for the correctness of consuming entire DER sequences, not sure we're entirely consistent (and have good coverage of) the `read_all()` aspect of things. (But I think this could help get that right in the future?)

### CODE REVIEW

**Review by cpu — COMMENTED** [review]
This looks like a nice tidy-up to me, thanks @djc!

Tiny nit: maybe squash the 3rd commit into the 1st and switch the usages over to the new pattern in one fell swoop?

**Comment by djc** [comment]
> Needs a thorough audit for the correctness of consuming entire DER sequences, not sure we're entirely consistent (and have good coverage of) the `read_all()` aspect of things. (But I think this could help get that right in the future?)

I spent some time looking at this and I think it's now correct. But review on these aspects would be good!

> Tiny nit: maybe squash the 3rd commit into the 1st and switch the usages over to the new pattern in one fell swoop?

Yup, good point -- done.

**Review by ctz — APPROVED** [review]
looks reasonable to me!

**Comment by djc** [comment]
@cpu hope this doesn't cause too much thrashing in your open PRs!

**Comment by cpu** [comment]
Nothing some git-fu won't solve :-)

**Pull request merged**
