### PR TITLE
Remember certificate policies extensions but do nothing further

### LINKED ISSUE #30: Support anyPolicy Certificate Policy
I'm dealing with a certificate that has critical Certificate Policy (2.5.29.32) with anyPolicy policy. It would be appreciated if rustls-webpki supported this scenario. Also created an issue in https://github.com/briansmith/webpki/issues/268.

NSS supports Certificate Policies with anyPolicy.

### PR DESCRIPTION
**Pull request by kikuomax**
Deal with certificate policies extensions so that `rustls-webpki` won't fail when it faces a critical certificate policies extensions.
- fixes #30

This PR makes `rustls-webpki` remember the values of the certificate policies extensions it faces but do nothing further. This change lets `rustls-webpki` accept certificates with invalid critical certificate policies extensions, though, this should be at least equivalent to [OpenSSL's default behavior](https://github.com/openssl/openssl/issues/21359).

If one wants to verify the policy tree, can use `verify_path` option to do so. You can find an [example in my fork](https://github.com/codemonger-io/webpki/blob/b0faf0db429262352761e653c377d9214bb46b57/tests/integration.rs#L142-L161).

### CODE REVIEW

**Review by djc — APPROVED** [review]
This looks okay to me.

If the test depends on the newly introduced behavior (not clear to me if it does?), I suggest that we switch the order of commits such that all commits can pass tests (since we rebase). (I suppose we could also just squash these commits.)

**Comment by ctz** [comment]
I don't think we should do this. The default openssl behaviour is incorrect and drives a bus through the intended meaning of extension criticality.

**Comment by kikuomax** [comment]
> I don't think we should do this. The default openssl behaviour is incorrect and drives a bus through the intended meaning of extension criticality.

I understand your concern. Integrity should not be compromised for a very specific use case.
@djc @ctz Is there any chance to have this as an opt-in feature like `accept-invalid-policies`?

Anyway, please reject this PR if it is not relevant.

**Comment by kikuomax** [comment]
> If the test depends on the newly introduced behavior (not clear to me if it does?), I suggest that we switch the order of commits such that all commits can pass tests (since we rebase). (I suppose we could also just squash these commits.)

@djc The order of commits reflected my test-driven approach. I will reorder them if this PR would be accepted.

**Comment by djc** [comment]
What exactly is the use case for this? Why would someone want to ignore these invalid extensions?

**Comment by cpu** [comment]
> What do the BRs say about the cert policy extension?

All of the locations in the server cert baseline requirements that describe this extension list it as non-critical:

* [7.1.2.1.2 Root CA Extensions - NOT RECOMMENDED, not critical](https://github.com/cabforum/servercert/blob/main/docs/BR.md#71212-root-ca-extensions)
* [7.1.2.2.3 Cross-Certified Subordinate CA Extensions - MUST presence, not critical](https://github.com/cabforum/servercert/blob/main/docs/BR.md#71223-cross-certified-subordinate-ca-extensions)
* [7.1.2.3.1 Technically Constrained Non-TLS Subordinate CA Extensions - MAY presence, not critical](https://github.com/cabforum/servercert/blob/main/docs/BR.md#71231-technically-constrained-non-tls-subordinate-ca-extensions)
* [7.1.2.4.1 Technically Constrained Precertificate Signing CA Extensions - MUST presence, not critical](https://github.com/cabforum/servercert/blob/main/docs/BR.md#71241-technically-constrained-precertificate-signing-ca-extensions)
* [7.1.2.5.1 Technically Constrained TLS Subordinate CA Extensions - MUST presence, not critical](https://github.com/cabforum/servercert/blob/main/docs/BR.md#71251-technically-constrained-tls-subordinate-ca-extensions)
* [7.1.2.7.6 Subscriber Certificate Extensions - MUST presence, not critical](https://github.com/cabforum/servercert/blob/main/docs/BR.md#71276-subscriber-certificate-extensions)
* [7.1.2.8.2 OCSP Responder Extensions - MUST NOT presence, not critical](https://github.com/cabforum/servercert/blob/main/docs/BR.md#71276-subscriber-certificate-extensions)

**Comment by kikuomax** [comment]
> What exactly is the use case for this? Why would someone want to ignore these invalid extensions?

@djc My use case is not client-server communication but server-side verification of signatures signed by authenticator devices in the context of [Web Authentication](https://www.w3.org/TR/webauthn-3/). I commented in Issue #30:
- https://github.com/rustls/webpki/issues/30#issuecomment-1827064164

The certificate policies in the certificate chain I attached to the above comment are valid, but the end entity certificate contains a critical certificate policy extension:
```
            X509v3 Certificate Policies: critical
                Policy: 1.3.6.1.4.1.311.21.31
                  User Notice:
                    Explicit Text:
```

I did not mean to make it accept invalid extensions, however, I need more study to propose comprehensive validation.

**Comment by cpu** [comment]
I think we should close this PR for now. I agree with [ctz's](https://github.com/rustls/webpki/pull/211#issuecomment-1827358947) earlier assessment.

**Comment by kikuomax** [comment]
@cpu Sorry for a stale PR. I would like to come back to this issue later.

**Pull request closed without merging**
