### PR TITLE
Preparation for ring 0.17 and untrusted 0.9

### PR DESCRIPTION
**Pull request by JackTemaki**
A starting point for https://github.com/rustls/webpki/issues/43.

https://github.com/briansmith/untrusted/commit/36f6dff818bd189e8ab9f57244da40a029d04673 removed equality checks do to security issues by potentially leaking timing information.

This requires checking in which cases the "unsafe" equality can stay and in which cases a constant check can/should be used.

(Two equality checks in test cases are still missing)

Options for  constant time equality checks are maybe:
https://docs.rs/constant_time_eq/latest/constant_time_eq/index.html
https://docs.rs/subtle/2.4.1/subtle/index.html
https://codeberg.org/valpackett/secstr/src/branch/trunk/src/lib.rs#L559

All implementations seem to work with different concepts.  As suggested by @djc , https://github.com/cesarb/constant_time_eq seems to be the most lighweight crate.

### CODE REVIEW

**Comment by djc** [comment]
@cpu or @ctz any thoughts on where/when we need constant-time comparisons?

**Comment by cpu** [comment]
> any thoughts on where/when we need constant-time comparisons?

I will try to give this some thought over the next few days.

>  As suggested by @djc , https://github.com/cesarb/constant_time_eq seems to be the most lighweight crate.

I might be missing some context, but is there a reason we can't use the `constant_time` module exported by *ring* instead of taking an additional dependency? 
https://docs.rs/ring/latest/ring/constant_time/fn.verify_slices_are_equal.html

**Comment by ctz** [comment]
I'm not really sure any comparisons that this crate does need constant-time comparison, since certificates, public keys, trusted certificates, etc are all effectively public data. There are some APIs for verifying signatures, but none of those should ever perform comparisons (again, public keys and signatures verifiable by them are public data).

With that all said, I think it would be most conservative of `untrusted` if equality of equal-length buffers was implemented in constant time. That is pessimistic in terms of performance, but not in a way that should matter.

**Comment by cpu** [comment]
> I'm not really sure any comparisons that this crate does need constant-time comparison, since certificates, public keys, trusted certificates, etc are all effectively public data.

That tracks :+1: 

> With that all said, I think it would be most conservative of untrusted if equality of equal-length buffers was implemented in constant time. That is pessimistic in terms of performance, but not in a way that should matter.

That sounds reasonable but unless we fork `untrusted` I don't think it will happen on a short time frame :-(

**Comment by JackTemaki** [comment]
> > As suggested by @djc , https://github.com/cesarb/constant_time_eq seems to be the most lighweight crate.
> 
> I might be missing some context, but is there a reason we can't use the `constant_time` module exported by _ring_ instead of taking an additional dependency? https://docs.rs/ring/latest/ring/constant_time/fn.verify_slices_are_equal.html

Ah sorry, I am not familiar with the ring repository. If you want I will replace the checks using this, otherwise I guess I can leave this PR as draft until ring 0.17 gets published.

**Comment by cpu** [comment]
> Ah sorry, I am not familiar with the ring repository. If you want I will replace the checks using this,

No worries :-) I just wanted to make sure it wasn't an option that was considered and rejected for some reason.

Based on ctz's response above I think making the comparisons constant time in webpki using ring's support for comparing equal length buffers safely is a good next step. It seems fair to be conservative and use constant time comparisons even if they're not strictly required. We can adjust as performance demands.

**Comment by cpu** [comment]
@JackTemaki Are you still interested in pursuing this PR or should it be shelved for now? Thanks!

**Comment by JackTemaki** [comment]
As it seems ring will not move to 0.17 soon I did not put a priority on this. I added `ring::constant_time::verify_slices_are_equal` to all checks in question now.

**Comment by cpu** [comment]
>  I added ring::constant_time::verify_slices_are_equal to all checks in question now.

I think there are some unit tests that also need to be updated to avoid `==` via `assert_eq!`. 

(Also needs a `cargo fmt` update I think).

**Comment by cpu** [comment]
I'm going to close this for now. There are a lot of conflicts and I don't think it makes sense to leave open pending a *ring* release. We can revive this effort when a Ring 0.17 release is available. Thanks!

**Pull request closed without merging**
