### PR TITLE
Don't distribute 3-clause BSD test artifacts

### LINKED ISSUE #101: clarify license: does BSD-3-Clause actually apply to crate sources?
Hi, I just noticed https://github.com/rustls/webpki/pull/77, since I'm packaging rustls-webpki for Fedora Linux.

I wonder why you have included both ISC *and* BSD-3-Clause in the crate metadata? As far as I can tell, BSD-3-Clause license only applies to test data, and not to any actual source code that is linked into applications. As such, I think the current `ISC AND BSD-3-Clause` is potentially misleading, especially for tools like `cargo-deny` or `cargo-license`, since it doesn't reflect the fact that no BSD-3-Clause licensed material actually ends up in compiled binaries.

If you think that crate metadata should still include BSD-3-Clause since you *are* redistributing BSD-licensed test data (even if they end up unused when downloaded from crates.io), it might be an option to exclude these data files and the tests that read them from published crates? That would also make download size for this crate noticably smaller.

### PR DESCRIPTION
**Pull request by ctz**
resolves #101

### CODE REVIEW

**Comment by djc** [comment]
After this branch we don't pass `cargo test` in the `target/package`. Do you intend to fix that?

**Comment by ctz** [comment]
I don't really have any good ideas for fixing that, short of taking new dependencies, exposing crate internals or introducing a build.rs. None of those feel very good.

**Review by djc — APPROVED** [review]

**Comment by djc** [comment]
We could do something with an internal feature that is disabled by default -- but I guess it's not that important.

**Comment by cpu** [comment]
I don't think I have enough context on the packaging side of the equation to weigh in on this one. Happy with whatever folks think is the best path forward.

**Pull request merged**
